name = "leetcode"
type = "javascript"
account_id = "897c203117fc45efa64b5eb52b3206e8"
zone_id = ""
workers_dev = true
route = ""
compatibility_date = "2021-12-07"
kv_namespaces = []

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"


# [build]
# command = "npm install && npm run build"

# [build.upload]
# format = "modules"
# main = "./index.mjs"
